version: '3.8'

services:
  seacarp-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "2222:22"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DISABLE_HTTPS=true
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro