version: '3.8'

services:
  seacarp-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
      - "22:22"
    environment:
      - IS_RUNNING_DOCKER=true
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro