using SeaCarp.ViewModels;

namespace SeaCarp.Controllers;

public class ChallengesController : Controller
{
    private readonly ILogger<ChallengesController> _logger;

    public ChallengesController(ILogger<ChallengesController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View(new string[] {
            "[SOURCE] Juice Shop",
            "API-only XSS",
            "Access Log",
            "Admin Registration",
            "Admin Section",
            "Arbitrary File Write",
            "Bjoern's Favorite Pet",
            "Blockchain Hype",
            "Blocked RCE DoS",
            "CAPTCHA Bypass",
            "Change Bender's Password",
            "Christmas Special",
            "CSP Bypass",
            "Client-side XSS Protection",
            "Confidential Document",
            "DOM XSS",
            "Database Schema",
            "Deprecated Interface",
            "Easter Egg",
            "Email Leak",
            "Ephemeral Accountant",
            "Error Handling",
            "Expired Coupon",
            "Extra Language",
            "Five-Star Feedback",
            "Forged Coupon",
            "Forged Feedback",
            "Forged Review",
            "Forged Signed JWT",
            "Forgotten Developer Backup",
            "Forgotten Sales Backup",
            "Frontend Typosquatting",
            "GDPR Data Erasure",
            "GDPR Data Theft",
            "HTTP-Header XSS",
            "Imaginary Challenge",
            "Leaked Access Logs",
            "Leaked Unsafe Product",
            "Legacy Typosquatting",
            "Login Admin",
            "Login Amy",
            "Login Bender",
            "Login Bjoern",
            "Login Jim",
            "Login MC SafeSearch",
            "Login Support Team",
            "Manipulate Basket",
            "Misplaced Signature File",
            "Multiple Likes",
            "Nested Easter Egg",
            "NoSQL DoS",
            "NoSQL Exfiltration",
            "NoSQL Manipulation",
            "Outdated Allowlist",
            "Password Strength",
            "Payback Time",
            "Premium Paywall",
            "Privacy Policy",
            "Privacy Policy Inspection",
            "Product Tampering",
            "Reflected XSS",
            "Repetitive Registration",
            "Reset Bender's Password",
            "Reset Bjoern's Password",
            "Reset Jim's Password",
            "Reset Morty's Password",
            "Retrieve Blueprint",
            "SSRF",
            "SSTi",
            "Score Board",
            "Security Policy",
            "Server-side XSS Protection",
            "Steganography",
            "Successful RCE DoS",
            "Supply Chain Attack",
            "Two Factor Authentication",
            "Unsigned JWT",
            "Upload Size",
            "Upload Type",
            "User Credentials",
            "Video XSS",
            "View Basket",
            "Vulnerable Library",
            "Weird Crypto",
            "Allowlist Bypass",
            "XXE Data Access",
            "XXE DoS",
            "Zero Stars",
            "Missing Encoding",
            "Cross-Site Imaging",
            "Exposed Metrics",
            "Deluxe Fraud",
            "CSRF",
            "Bonus Payload",
            "Reset Uvogin's Password",
            "Meta Geo Stalking",
            "Visual Geo Stalking",
            "Kill Chatbot",
            "Poison Null Byte",
            "Bully Chatbot",
            "Local File Read",
            "Mass Dispel",
            "------------------------------------------------------------------------------------------------",
            "[SOURCE] MITRE",
            "CWE 79: XSS (https://cwe.mitre.org/data/definitions/79.html)",
            "CWE 78: OS Command Injection (https://cwe.mitre.org/data/definitions/78.html)",
            "CWE 22: Path Traversal (https://cwe.mitre.org/data/definitions/22.html)",
            "CWE 352: CSRF (https://cwe.mitre.org/data/definitions/352.html)",
            "CWE 434: Unrestricted Upload of File Type (https://cwe.mitre.org/data/definitions/434.html)",
            "CWE 476: NULL Pointer Dereference (https://cwe.mitre.org/data/definitions/476.html)",
            "CWE 502: Deserialization of Untrusted Data (https://cwe.mitre.org/data/definitions/502.html)",
            "CWE 190: Integer Overflow or Wraparound (https://cwe.mitre.org/data/definitions/190.html)",
            "CWE 287: Improper Authentication (https://cwe.mitre.org/data/definitions/287.html)",
            "CWE 862: Missing Authorization (https://cwe.mitre.org/data/definitions/862.html)",
            "CWE 77: Command Injection (https://cwe.mitre.org/data/definitions/77.html)",
            "CWE 306: Missing Authentication for Critical Function (https://cwe.mitre.org/data/definitions/306.html)",
            "CWE 276: Incorrect Default Permissions (https://cwe.mitre.org/data/definitions/276.html)",
            "CWE 918: SSRF (https://cwe.mitre.org/data/definitions/918.html)",
            "CWE 362: Race Condition (https://cwe.mitre.org/data/definitions/362.html)",
            "CWE 400: Uncontrolled Resource Consumption (https://cwe.mitre.org/data/definitions/400.html)",
            "CWE 611: Improper Restriction of XML External Entity Reference (https://cwe.mitre.org/data/definitions/611.html)",
            "CWE 94: Code Injection (https://cwe.mitre.org/data/definitions/94.html)",
            "CWE 89: SQL Injection (https://cwe.mitre.org/data/definitions/89.html)",
            "CWE 20: Improper Input Validation (https://cwe.mitre.org/data/definitions/20.html)",
            "------------------------------------------------------------------------------------------------",
            "[SOURCE] OWASP TOP 10",
            "Broken Access Control",
            "Cryptographic Failures",
            "Injection",
            "Insecure Design",
            "Security Misconfiguration",
            "Vulnerable and Outdated Components",
            "Identification and Authentication Failures",
            "Software and Data Integrity",
            "Security Logging and Monitoring",
            "Server-Side Request Forgery",
            "------------------------------------------------------------------------------------------------",
            "[SOURCE] OWASP API TOP 10",
            "BROKEN OBJECT LEVEL AUTHORIZATION",
            "BROKEN AUTHENTICATION",
            "EXCESSIVE DATA EXPOSURE",
            "LACK OF RESOURCES & RATE LIMITING",
            "BROKEN FUNCTION LEVEL AUTHORIZATION",
            "MASS ASSIGNMENT",
            "SECURITY MISCONFIGURATION",
            "INJECTION",
            "IMPROPER ASSETS MANAGEMENT",
            "INSUFFICIENT LOGGING & MONITORING",
            "------------------------------------------------------------------------------------------------",
            "[SOURCE] Misc",
            "CSP bypass: https://portswigger.net/research/bypassing-csp-with-policy-injection"
        });
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}